config/routes.rb
Twitter::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'users#destroy', as: 'logout'

  root :to => 'users#index'

  resources :users do
    resources :tweets
    resources :followers, :only => [:create, :destroy]
  end

  resources :sessions

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :message, :presence => true

  def message_split(message)
    words = message.split(' ')
    @new_words = []
    rgx = /\@(.+)$/

    words.each do |word|
      if word.match(rgx)
        @new_words << word.split('@')[1]

      end
    end

    @new_words.length > 0

  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :tweets
  has_many :followers

  validates :name, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true


  has_attached_file :avatar, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  after_save :slugger
  # acts_as_url :slug

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end

private

  def slugger
    self.slug = self.name.parameterize
    self.update_column(:slug, self.slug)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      current_user ||= User.find(session[:user_id]) if session[:user_id]
      # current_user = nil
    end

    helper_method :current_user


    def authorize
      redirect_to new_session_path, alert: "Not authorized" if current_user.nil?
    end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def create
    @follower = User.find(params[:follower_id])
    @user = User.find(params[:user_id])
    @user.followers.create(follower_id: @follower.id)
    redirect_to users_path
  end

  def destroy
    @follower = User.find(params[:id])
    @user = User.find(params[:user_id])
    Follower.destroy_all({user_id: @user.id, follower_id: @follower.id})
    # @deleteme.destroy
    # @user.followers.destroy(@follower)
    redirect_to users_path
  end

  private
    # def follower_params
    #   params.require[:follower]
    # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :must_login,  only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


  def index

  end

  def create
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.create(tweet_params)

    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.js
    end

  end

  private
    def tweet_params
      params.require(:tweet).permit(:message, :photo)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    @users = User.all.reject {|x| x == current_user }
    @following = Follower.where(:follower_id => current_user.id)
    @leaders = @following.pluck(:user_id)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.find(:all, :order => 'created_at').reverse
    @tweet = Tweet.new

    @following = Follower.where(:follower_id => @user.id)
    @leaders = @following.pluck(:user_id)

    feed_tweets = []
    Tweet.all.each do |tweet|
      if @leaders.include?(tweet.user_id)
        feed_tweets << tweet
      end
    end

    @feed_tweets = feed_tweets.sort_by &:created_at
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="naviHeader">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-left">
              <li><a href="/">Twitter</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
               <li><%= link_to current_user.name, user_path(current_user) %></li>
               <li><a href="javascript:void(0);" data-toggle="modal" data-target="#newTweet" ><span class="glyphicon glyphicon-plus"></span> Add Tweet</a></li>
               <li></li>
               <li><%= link_to 'Logout', session_path('current'), method: 'delete' %></li>
              <% else %>
                <li><%= link_to 'Login', new_session_path %></li>
                <li><%= link_to 'Register', new_user_path %><li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Russo+One|Quantico:400,700' rel='stylesheet' type='text/css'>



</head>
<body>

  <%= render 'layouts/header' %>

  <div id="wrapper" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tweets/_tweet.html.erb
<div class="tweet-display">
    <%= @tweet.message %>
    <span class="tweet-time">Tweeted <%= time_ago_in_words(@tweet.created_at) %> ago</span>
    <div class="clear"></div>
</div>

app/views/tweets/create.js.erb
$('#my-tweets h3').after('<%= j render(@tweet) %>');
$('#new_tweet textarea').val('')

if ($('.modal').is(':visible')) {
  $('.modal').hide();
  $('.modal-backdrop').hide()
};

app/views/tweets/index.html.erb
<h1>Whatever</h1>

app/views/users/index.html.erb
<div id="user-list">
  <% @users.each do |user| %>
    <div class="display-user-tweets col-md-7">
      <%= link_to user.name, user_path(user) %>
      <% if current_user %>
      <% if @leaders.include?(user.id) &&   %>
        <%= link_to 'Unfollow', user_follower_path(user, current_user), method: 'delete', class: 'follow-user' %>
      <% else %>
        <%= link_to 'Follow', user_followers_path(user, :follower_id => current_user.id), method: 'post', class: 'follow-user' %>
      <% end %>
      <% end %>
      <%
        user_tweets_length = user.tweets.length
        if user_tweets_length > 3 ? user_tweets_length = 3 : user_tweets_length = user_tweets_length
      %>
        <% user.tweets[-user_tweets_length,user_tweets_length].each do |tweet| %>
          <div class="tweet-display">
            <%= tweet.message %>
            <span class="tweet-time">Tweeted <%= time_ago_in_words(tweet.created_at) %> ago</span>
            <div class="clear"></div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Sign Up </h1>

    <%= form_for @user, role: 'form' do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, 'Full Name:', class: 'sr-only' %>
        <%= f.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email:', class: 'sr-only' %>
        <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password:', class: 'sr-only' %>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Password Confirm:', class: 'sr-only' %>
        <%= f.password_field :password_confirmation, placeholder: 'Password Confirm', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :avatar, 'Avatar:', class: 'sr-only' %>
        <%= f.file_field :avatar, class: 'form-control' %>
      </div>
      <%= f.submit "Register", :class => 'btn btn-info' %>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <div class="col-md-3">
    <h1><%= @user.name %></h1>
    <%= image_tag @user.avatar(:thumb) %>
  </div>
  <div class="col-md-6">
      <%= form_for [@user, @tweet], :role => 'form', :remote => true, :multipart => true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'New Tweet:', class: 'sr-only' %>
          <%= f.text_area :message, placeholder: 'New Tweet', class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
        <% if current_user == @user %>
<% end %>
  </div>
</div>

<div class="clear"></div>
<hr>
<div class="row">
  <div class="col-md-6">
    <div id="my-tweets">
      <h3>My Tweets</h3>
      <% @tweets.each do |tweet| %>
        <div class="tweet-display">
          <%= tweet.message %>
          <span class="tweet-time">Tweeted <%= time_ago_in_words(tweet.created_at) %> ago</span>
          <div class="clear"></div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <h3>My Feed</h3>
      <% @feed_tweets.reverse.each do |tweet| %>
        <div class="tweet-display">
            <%= tweet.message %>
            <span class="tweet-time">Tweeted <%= time_ago_in_words(tweet.created_at) %> ago by <%= tweet.user.name %></span>
            <div class="clear"></div>
          </div>
      <% end %>
  </div>

  <div class="col-md-6">
    <h3>My Mentions</h3>
      <% @feed_tweets.reverse.each do |tweet| %>
        <% if tweet.message_split(tweet.message) %>
          <div class="tweet-display">
              <%= tweet.message %>
              <span class="tweet-time">Tweeted <%= time_ago_in_words(tweet.created_at) %> ago by <%= tweet.user.name %></span>
              <div class="clear"></div>
            </div>
        <% end %>
      <% end %>
  </div>



</div>

<div class="modal fade" id="newTweet" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">New Tweet</h4>
        </div>
        <div class="modal-body">
          <%= form_for [@user, @tweet], :role => 'form', :remote => true, :html => { :multipart => true } do |f| %>
            <div class="form-group">
              <%= f.label :name, 'New Tweet:', class: 'sr-only' %>
              <%= f.text_area :message, placeholder: 'Say something...', class: 'form-control' %>
            </div>
            <%= f.submit 'Submit', class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>